### ISSUE TITLE
License Enforcement

### ISSUE THREAD

**Issue by jdewinne** [repcollab/subsalt-replicated#3]
### Problem to solve

Manage customers who are licensed to run Subsalt on prem, enforcing trial conditions and license expirations

### Tasks

- [ ] Complete Lab 0
- [ ] Complete Lab 9
- [ ] Create customer in Vendor Portal
- [ ] Add custom field to a customer
- [ ] Discuss: Use license API in kotsadm

### Additional Resources or Documentation

https://docs.replicated.com/vendor/releases-creating-customer
