### ISSUE TITLE
Advanced Updates

### ISSUE THREAD

**Issue by jdewinne** [repcollab/subsalt-replicated#9]
### Problem to solve

Now that we've verified the one-click updates in Replicated App Manager, let's explore the automatic updates feature

### Tasks

- [ ] Validate simple one-click updates in Lab 0
- [ ] Enable Automatic Updates on a dev instance
- [ ] Publish a release and validate automatic updates
- [ ] (best practices discussion) how to use semver for automatic updates
- [ ] (best practices discussion) explore how failed preflights will block automatic updates

### Additional Resources or Documentation

https://docs.replicated.com/enterprise/updating-apps#update-an-application-in-the-admin-console
